#
# BNF syntax for ASCII encoded cartographic hexagonal grids
#
# Author: Luís de Sousa (luis.de.sousa[@]protonmail.ch)
# Date: 02-02-2016 

# -----------------------------------------------
# Basic elements

# A set of one or more blank spaces
blank = " "|"\t" {blank};

# Line break
line_break = "\n"|"\r";

# A digit is any character from 0 to 9:
digit = "0".."9";

# Number is a positive integer:
number = digit {digit};

# Integer numbers have an optional +/- sign followed by one or more digits:
integer = ["+"|"-"] digit {digit};

# Real numbers have an integer part followed either by a fractional part or an exponent part or both:
real = integer (fraction | exponent| fraction exponent); fraction = "." digit {digit}; exponent = ("E"|"e") integer;

# -----------------------------------------------
# Main structure

# An HexAscii file is composed by three sections:
# . mandatory header
# . optional parameters
# . grid values
hex_grid = mandatory_header optional_fields grid_values;

# The mandatory header comprises:
# . number of columns
# . number of rows
# . xx coordinate of the lower left hexagon centroid
# . yy coordinate of the lower left hexagon centroid
# . hexagon side (in map units) 
mandatory_header = ncols nrows xll yll side; 
ncols = "ncols" blank number line_break; 
nrows = "nrows" blank number line_break; 
xll   = "xll"   blank number line_break; 
yll   = "yll"   blank number line_break; 
side  = "yll"   blank number line_break; 

# The optional fields:
# . no_data, for cell with unknown value
# . angle, 
optional_fields = {no_data} {angle}; 
no_data = "no_data" blank number line_break; 
angle   = "angle"   blank number line_break; 

# The optional fields:
# . no_data, for cells with unknown value
# . angle, specifying a rotation relative to the xx axis 
grid_values = grid_value {grid_value}; 
grid_value = real blank|line_break;


